_target_: src.models.mnist_module.GenerativeModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.diffusion.DDPM
  in_channels: 1
  hidden_channels: 32
  out_channels: 1
  time_dim: 1000

compile: false
